### ISSUE TITLE
Deprecated selector in `firacode/styles/firacode.less`

### ISSUE THREAD

**Issue by ggPeti** [adilparvez/atom-firacode#1]
(Atom made me do this)

In `firacode/styles/firacode.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `[firacode-font='firacode-light'] atom-text-editor::shadow .comment` => `[firacode-font='firacode-light'] atom-text-editor.editor .syntax--comment`

* `[firacode-font='firacode-light'] atom-text-editor::shadow .string` => `[firacode-font='firacode-light'] atom-text-editor.editor .syntax--string`

* `[firacode-font='firacode-regular'] atom-text-editor::shadow .comment` => `[firacode-font='firacode-regular'] atom-text-editor.editor .syntax--comment`

* `[firacode-font='firacode-regular'] atom-text-editor::shadow .string` => `[firacode-font='firacode-regular'] atom-text-editor.editor .syntax--string`

* `[firacode-font='firacode-retina'] atom-text-editor::shadow .comment` => `[firacode-font='firacode-retina'] atom-text-editor.editor .syntax--comment`

* `[firacode-font='firacode-retina'] atom-text-editor::shadow .string` => `[firacode-font='firacode-retina'] atom-text-editor.editor .syntax--string`

* `[firacode-font='firacode-medium'] atom-text-editor::shadow .comment` => `[firacode-font='firacode-medium'] atom-text-editor.editor .syntax--comment`

* `[firacode-font='firacode-medium'] atom-text-editor::shadow .string` => `[firacode-font='firacode-medium'] atom-text-editor.editor .syntax--string`

* `[firacode-font='firacode-bold'] atom-text-editor::shadow .comment` => `[firacode-font='firacode-bold'] atom-text-editor.editor .syntax--comment`

* `[firacode-font='firacode-bold'] atom-text-editor::shadow .string` => `[firacode-font='firacode-bold'] atom-text-editor.editor .syntax--string`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by adilparvez** [comment]
Thank you very much for the report, I'll fix this tomorrow.

**Comment by adilparvez** [comment]
Fixed.
