### ISSUE TITLE
JS special symbols edge-case

### ISSUE THREAD

**Issue by TwoAbove** [adilparvez/atom-firacode#2]
Hey! There are some edge cases that seem to not to work as intended.

Here's an example:

![capture](https://cloud.githubusercontent.com/assets/9610438/26204345/24191d1c-3be7-11e7-80b1-767069c35c14.PNG)

Lines 1-3 are correct, line 4 is not.

On the fourth line in the `${}` brackets there can be code, so it should look like line one. This syntax appears only with the backlashes

**Comment by adilparvez** [comment]
Thanks for reporting this. I'll fix this, and update the package soon.

**Comment by TwoAbove** [comment]
Just in case --  [Here is the template syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

**Comment by adilparvez** [comment]
As a temporary fix you can add the following to your stylesheet (`File > Stylesheet`).

```less
atom-text-editor {
  // Fix for JavaScript (source.js).
  .syntax--string.syntax--quoted.syntax--template.syntax--js
  > .syntax--source.syntax--js.syntax--embedded {
    font-feature-settings: 'liga' on, 'calt' on;
  }

  // Fix for JavaScript with JSX (source.js.jsx).
  .syntax--string.syntax--quoted.syntax--other.syntax--es6
  > .syntax--meta.syntax--embedded.syntax--expression.syntax--es6 {
    font-feature-settings: 'liga' on, 'calt' on;
  }
}
```

**Comment by TwoAbove** [comment]
Looks good! But there's a catch -- The usual quotes are now pretty, too
(not sure that's a bad thing, tho 😃)
![image](https://cloud.githubusercontent.com/assets/9610438/26423333/f0df56ca-40d5-11e7-82e8-d357eb111b7e.png)

**Comment by adilparvez** [comment]
I'll investigate further, it seems to work for me.

![template-string-ligatures](https://cloud.githubusercontent.com/assets/6894766/26441989/9c476d96-412a-11e7-93d3-50b73e90c0ec.png)

**Comment by TwoAbove** [comment]
I'm sure this should be closed ages ago
